name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
      - name: Build with Maven
        run: mvn clean package
      - name: Deploy to Tomcat
        run: |
          ssh -i /path/to/key.pem ubuntu@http://15.207.71.25:9090/ << 'EOF'
          rm -rf /opt/tomcat/webapps/addressbook*
          cp target/addressbook.war /opt/tomcat/webapps/
          EOF
